version: '2'

services:
  javademo-img:
    image: liangguo/javademo-img
    restart: always
    volumes:
      - ./data:/data
    ports:
      - "8881:80"
      
  javademo:
    image: liangguo/javademo
    restart: always
    ports:
      - "8880:8080"
    environment:
      CATALINA_OPTS: "-Dimgserver=http://10.100.6.3:8881/img/"
